### ISSUE TITLE
ExVatcheck.check causes process to exit

### ISSUE THREAD

**Issue by danielkirch** [taxjar/ex_vatcheck#12]
Running `ExVatcheck.check` for a VAT with correct format currently causes the process to exit.

```
iex(1)> ExVatcheck.check("DE123456789")
[error] 3957- fatal: {:error, {:whitespace_was_expected}}

** (exit) {:fatal, {{:error, {:whitespace_was_expected}}, {:file, :file_name_unknown}, {:line, 1}, {:col, 55}}}
    (xmerl 1.3.29) xmerl_scan.erl:4127: :xmerl_scan.fatal/2
    (xmerl 1.3.29) xmerl_scan.erl:1209: :xmerl_scan.scan_doctype1/2
    (xmerl 1.3.29) xmerl_scan.erl:730: :xmerl_scan.scan_prolog/4
    (xmerl 1.3.29) xmerl_scan.erl:571: :xmerl_scan.scan_document/2
    (xmerl 1.3.29) xmerl_scan.erl:294: :xmerl_scan.string/2
    (sweet_xml 0.7.3) lib/sweet_xml.ex:292: SweetXml.do_parse/2
    (sweet_xml 0.7.3) lib/sweet_xml.ex:281: SweetXml.parse/2
    (ex_vatcheck 0.2.1) lib/ex_vatcheck/xml.ex:7: ExVatcheck.Xml.parse/3
    (ex_vatcheck 0.2.1) lib/ex_vatcheck/vies_client/xml_parser.ex:92: ExVatcheck.VIESClient.XMLParser.parse_response/1
    (ex_vatcheck 0.2.1) lib/ex_vatcheck.ex:30: ExVatcheck.validate/1
```

In `lib/ex_vatcheck/vies_client.ex:30` a post is made to an external service which is apparently not available at the moment and thus returns a 500 error code together with an html response. The attempt to parse the response with xmerl causes the process to exit (which imo is not expected behaviour either, but an issue in xmerl).

This is the html response:
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Draft//EN">
<HTML>
<HEAD>
<TITLE>Error 500--Internal Server Error</TITLE>
</HEAD>
<BODY bgcolor="white">
<FONT FACE=Helvetica><BR CLEAR=all>
<TABLE border=0 cellspacing=5><TR><TD><BR CLEAR=all>
<FONT FACE="Helvetica" COLOR="black" SIZE="3"><H2>Error 500--Internal Server Error</H2>
</FONT></TD></TR>
</TABLE>
<TABLE border=0 width=100% cellpadding=10><TR><TD VALIGN=top WIDTH=100% BGCOLOR=white><FONT FACE="Courier New"><FONT FACE="Helvetica" SIZE="3"><H3>From RFC 2068 <i>Hypertext Transfer Protocol -- HTTP/1.1</i>:</H3>
</FONT><FONT FACE="Helvetica" SIZE="3"><H4>10.5.1 500 Internal Server Error</H4>
</FONT><P><FONT FACE="Courier New">The server encountered an unexpected condition which prevented it from fulfilling the request.</FONT></P>
</FONT></TD></TR>
</TABLE>

</BODY>
</HTML>
```

**Comment by jakedjohnson** [comment]
@danielkirch Seems like VIES changed their SOAP envelope without telling anyone, which caused both the request to fail and SweetXml couldn't parse the new XML prefixes. 

[I have a PR fix up](https://github.com/taxjar/ex_vatcheck/pull/13) for this and a `0.3.1` tag in the repo.
